name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tsh
            asset_name: tsh-linux-amd64
          - os: windows-latest
            artifact_name: tsh.exe
            asset_name: tsh-windows-amd64
          - os: macos-latest
            artifact_name: tsh
            asset_name: tsh-macos-amd64

    steps:
    - uses: actions/checkout@v2

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - name: Compile
      run: deno compile --unstable --allow-all --output ${{ matrix.artifact_name }} main.ts

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.DEPLOY_PAT }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}